version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "docker-volumes/mysql/data:/var/lib/mysql"
      - "docker-volumes/mysql/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "docker-volumes/redis/data:/data"
      - "docker-volumes/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      redis-server /usr/local/etc/redis/redis.conf

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://dev.kafka.java110.com:9092
