version: "3.7"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    volumes:
      - "~/grasswort-env/docker-volumes/metabase/data:/metabase-data"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db

