version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "~/grasswort-env/docker-volumes/mysql/data:/var/lib/mysql"
      - "~/grasswort-env/docker-volumes/mysql/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890