version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - "~/grasswort-env/docker-volumes/redis/data:/data"
      - "~/grasswort-env/docker-volumes/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      redis-server /usr/local/etc/redis/redis.conf